# Generated by Django 6.0.6 on 2026-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_on_projects_page',
            field=models.BooleanField(default=False, verbose_name='Отображать на странице проектов'),
        ),
    ]
